// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-vz6POYQ1s1NcrgJZ01A8xucEu8vG56w',
    appId: '1:333875197359:web:2654582460492b37e32b5a',
    messagingSenderId: '333875197359',
    projectId: 'financiera-efectiva-movil',
    authDomain: 'financiera-efectiva-movil.firebaseapp.com',
    storageBucket: 'financiera-efectiva-movil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRdhWXmGzQBOEvbYRn5lahe5nzpUN92DM',
    appId: '1:333875197359:android:07193774d89655b1e32b5a',
    messagingSenderId: '333875197359',
    projectId: 'financiera-efectiva-movil',
    storageBucket: 'financiera-efectiva-movil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8yjiGEUw5nD5K7A2gqyJbkbOC7YHinbI',
    appId: '1:333875197359:ios:257754ce26726ddde32b5a',
    messagingSenderId: '333875197359',
    projectId: 'financiera-efectiva-movil',
    storageBucket: 'financiera-efectiva-movil.firebasestorage.app',
    iosBundleId: 'com.example.financieraEfectiva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8yjiGEUw5nD5K7A2gqyJbkbOC7YHinbI',
    appId: '1:333875197359:ios:257754ce26726ddde32b5a',
    messagingSenderId: '333875197359',
    projectId: 'financiera-efectiva-movil',
    storageBucket: 'financiera-efectiva-movil.firebasestorage.app',
    iosBundleId: 'com.example.financieraEfectiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-vz6POYQ1s1NcrgJZ01A8xucEu8vG56w',
    appId: '1:333875197359:web:cb15d95518bf3b50e32b5a',
    messagingSenderId: '333875197359',
    projectId: 'financiera-efectiva-movil',
    authDomain: 'financiera-efectiva-movil.firebaseapp.com',
    storageBucket: 'financiera-efectiva-movil.firebasestorage.app',
  );
}
